shopapp.webui/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using shopapp.entity;

namespace shopapp.webui.Models
{
    public class PageInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public string CurrentCategory { get; set; }
        public int TotalPages()
        {
             return (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage);
        }
    }
    public class ProductListViewModel
    {
        public PageInfo PageInfo { get; set; }
        public List<Product> Products { get; set; }
    }
}

shopapp.webui/Models/SharedViewModel.cs
using System.Collections.Generic;
using shopapp.entity;

namespace shopapp.webui.Models
{
    public class SharedViewModel
    {
        public string ComMail { get; set; }
        public string ComAdres { get; set; }
        public string ComNumara { get; set; }
    }
}

shopapp.webui/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    public class CompanyController: Controller
    {
        private ICompanyService _companyService;
        public CompanyController(ICompanyService companyService)
        {
            this._companyService=companyService;
        }
        public IActionResult Index()
        {
            var companyViewModel = new CompanyListViewModel()
            {
                Companies = _companyService.GetAll()
            };

            return View(companyViewModel);
        }

     
    }
}

shopapp.webui/Controllers/ServeController.cs
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    public class ServeController:Controller
    {
        private IServeService _serveService;
        public ServeController(IServeService serveService)
        {
            this._serveService=serveService;
        }
        public IActionResult Index()
        {
            var serveViewModel = new ServeListViewModel()
            {
                Serves = _serveService.GetAll()
            };
            return View(serveViewModel);
        }
    }
}

shopapp.webui/ViewComponents/CompaniesViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;

namespace shopapp.webui.ViewComponents
{
    public class CompaniesViewComponent: ViewComponent
    {
        private ICompanyService _companyService;
        public CompaniesViewComponent(ICompanyService companyService)
        {
            this._companyService=companyService;
        }
        public IViewComponentResult Invoke()
        {
            return View(_companyService.GetAll());
        }
    }
}

shopapp.webui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-language" content="tr" />
    <meta name="author" content="X Study" />
    <meta name="copyright" content="X Study" />
    <meta name="abstract" content="Yurtdışı Eğitim Danışmanlığı" />
    <meta name="robots" content="index, follow" />
    <meta property="og:title" content="Yurtdışı Eğitim Yurtdışı Eğitim Danışmanlığı" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="X Study" />
    <title>Yurtdışı Eğitim Danışmanlığı Yurtdışı Eğitim Programları | X Study</title>
    <meta name="description" content="Yurdışı Eğitim Yurtdışı Eğitim Danışmanlığı Yurtdışı Eğitim Programları">
    <meta name="keywords" content="yurtdışı, yurtdışı eğitim, yurtdışı eğitim danışmanlığı, yurtdışı eğitim programları,
    yurtdışı eğitim ücretleri, ukrayna eğitim, ukraynada eğitim, ukrayna eğitim danışmanlığı, ukrayna eğitim programları,
    rusya eğitim, rusyada eğitim, rusya eğitim danışmanlığı, rusya eğitim programları, belarus eğitim, belarus eğitim danışmanlığı,
    belarus eğitim programları" />

   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css">

    

</head>
<body>

    @await Html.PartialAsync("_navbar")          
    <main class="mb-3">
        <div class="container">     
            @if(TempData["message"]!=null)
            {
                var message = JsonConvert.DeserializeObject<AlertMessage>(TempData["message"] as String);
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-@message.AlertType">
                            @message.Message
                        </div>
                    </div>
                </div>
            }      
         @RenderBody()    
        </div>
    </main>

    <div class="container">
        @await Component.InvokeAsync("Companies")
    </div>
    

    <footer class="py-5 bg-dark text-white text-center">
        Copyright © Sami Karakul 2020
    </footer>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
     integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
     
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    @RenderSection("Scripts",false)
</body>
</html>

shopapp.webui/Views/Shared/_carousel.cshtml
    <div id="slider1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/img/2.jpg" alt="yurtdisi-egitim yurtdışı eğitim"/>
            </div>

            <div class="carousel-item">
                <img class="d-block w-100" src="~/img/england.jpg" alt="yurtdisi-egitim-danismanligi yurtdışı eğitim danışmanlığı" />
            </div>

        </div>
        <a href="#slider1" class="carousel-control-prev" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a href="#slider1" class="carousel-control-next" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>

shopapp.webui/Views/Shared/_categories.cshtml
 @model List<Category>
 
<ul>
    <li style="display: inline-block !important;">
        @foreach (var category in Model)
        {
            <a href="#" class="">@category.Name</a>
        }
    </li>
</ul>

shopapp.webui/Views/Shared/_categoryView.cshtml
@model Category

<div class="card my-2" style="border:none;">
    <img class="card-img-top" src="~/img/@Model.CategoryImageUrl" alt="@Model.Name-egitim eğitim"  style="height:300px;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
    </div>
</div>   

shopapp.webui/Views/Shared/_company.cshtml
@model Company

<partial name="_companyab">

shopapp.webui/Views/Shared/_companyab.cshtml
<div class="pt-5">
        <hr>
        <h1 class="text-center py-5">Neden bizi seçmelisiniz?</h1>
        <hr>
    <div class="container pt-5">
        <div class="row py-3">
            <div class="col-5">
                <img src="~/img/yurtdisi-egitim-danismanligi.jpg" alt="yurtdisi-egitim-danismanligi eğitim yurtdışı"  style="width:100%;">
            </div>
            <div class="col-7">
                Güvenilir <b>Yurtdışı Eğitim Danışmanlığı</b> ile Kariyeriniz İçin Doğru Adımları Atın!
            </div>
        </div>
        <div class="row py-3">
            <div class="col-5">
                <img src="~/img/yurtdisinda-egitim.jpg" alt="yurtdisi-egitim yurtdışı eğitim" style="width:100%;">
            </div>
            <div class="col-7">
               Çeşitlendirilmiş <b>Yurtdışı Programları</b> ile Sizin İçin Doğru Yurtdışı Eğitim Programı'nı seçebilirsiniz!!
            </div>
        </div>
        <div class="row py-3">
            <div class="col-5">
                <img src="~/img/yurtdisi.jpg" alt="yurtdisi-egitim yurtdışı eğitim" style="width:100%;">
            </div>
            <div class="col-7">
                Endişelendirmeyen Ücretlendirmeler!<b>Yurtdışı Eğitim Ücretleri</b> hakkında detaylı bilgilendirme için bize ulaşın!
            </div>
        </div>
    </div>
    <div class="text-center pt-5">
        <hr>
        <h2 class="py-5">Daha Detaylı Bilgi Edinmek İçin Bize Ulaşın!</h2>
        <hr>
    </div>
</div>

shopapp.webui/Views/Shared/_education.cshtml
<div class="text-center pt-3">
    <hr>
    <h1 class="py-5">Neden Yurtdışında Eğitim Almalısınız?</h1>
    <hr>
</div>
<div class="container pt-5">
    <div class="row my-3">
        <div class="col-5">
            <img src="~/img/yurtdisi.jpg" alt="yurtdisi-egitim yurtdışı eğitim" style="width:100%;">
        </div>
        <div class="col-7">
                Yurtdışı Eğitim getirilerinden bir tanesi, seçeneğinizin artacak olması. 
                Farklı <a href="/ulkeler">ülkelerdeki</a> eğitimcilerden göreceğiniz eğitimler ufkunuzu genişletecek.
                <br> 
        </div>
    </div>
    <div class="row my-3">
        <div class="col-5">
            <img src="~/img/yurtdisi-egitim.jpg" alt="yurtdisi-egitim  eğitim yurtdışı" style="width:100%;">
        </div>
        <div class="col-7">
            Alanında kendini kanıtlamış <a href="/universiteler">üniversitelerden</a> alacağınız eğitim ile
            Mesleki Kariyer Planınızı Geniş Çerçeveden İzleme ve Gelişme İmkanı kazanacaksınız.
        </div>
    </div>
    <div class="row my-3">
        <div class="col-5">
            <img src="~/img/yurtdisi-egitim-programlari.jpg" alt="yurtdisi-egitim-danismanligi yurtdışı eğitim danışmanlığı" style="width:100%;">
        </div>
        <div class="col-7">
                Alacağınız <b>Yurtdışı Eğitim</b> Sayesinde Durmaksınız Büyüyen Dünya ile Aynı Adımları Atmaya Başlayacaksınız.
        </div>
    </div>
</div>

shopapp.webui/Views/Shared/_header.cshtml
 <header class="pt-5">
        <div class="jumbotron jumbotron-fluid pt-5">
            <div class="container">
                <h1 class="display-4">X Study</h1>
                <p class="lead"><b>Yurtdışı Eğitim Danışmanlığı</b> yapan X Study Ülkemizin Öğrencilerini
                Farklı Ülkelerin Öğrencileriyle Buluşturup Kaliteli Eğitim Almalarını Hedefliyor. <b>Yurtdışı Eğitim</b>
                İmkanlarını Ülkemizin Öğrencileriyle Buluşturup Aldıkları Eğitimden Memnun Olmaları En Büyük Gayemizdir.
                Yurtdışı Eğitim Programları hakkında daha fazla bilgi için, <a href="/programlar">tıklayın.</a></p>
            </div>
        </div>
    </header>

shopapp.webui/Views/Shared/_navbar.cshtml
<div class="navbar bg-danger navbar-dark navbar-expand-sm mb-3" style="position:fixed; z-index:50; width:100%;" >
        <div class="container">
            <a href="/" class="navbar-brand">X Study</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link willh"><i class="fas fa-bars"></i></a>
                    <ul class="navbar-nav mr-auto dropdown">
                        <li class="nav-item">
                            <a href="/universiteler" class="nav-link">Üniversiteler</a>
                        </li>
                        <li class="nav-item">
                            <a href="/ulkeler" class="nav-link">Ülkeler</a>
                        </li>        
                        <li class="nav-item">
                            <a href="/hakkimizda" class="nav-link">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a href="/programlar" class="nav-link">Programlarımız</a>
                        </li>
                        
                    </ul>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto">
                @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="#" class="nav-link">Düzenleme işlemleri</a>
                                <ul class="navbar-nav mr-auto dropdown1">
                                    <li class="nav-item">
                                    <a href="/admin/products" class="nav-link">Üniversiteleri Düzenle</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/admin/categories" class="nav-link">Ülkeleri Düzenle</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/admin/companies" class="nav-link">Bilgileri Düzenle</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/admin/serves" class="nav-link">Programları Düzenle</a>
                                    </li>
                                    
                                </ul>
                            </li>
                        }
            </ul>
            <ul class="navbar-nav ml-auto">

                @if(User.Identity.IsAuthenticated)
                {
                     <li class="nav-item">
                        <a href="/account/logout">Çıkış Yap</a>
                    </li>
                } 
                else
                {
                    <li class="nav-item">
                        <a href="/account/login">Giriş Yap</a>
                    </li>
                }
            </ul>
        </div>
    </div>

shopapp.webui/Views/Shared/_noproduct.cshtml
 <div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            Ürün yok    
        </div>
    </div>
</div>

shopapp.webui/Views/Shared/_product.cshtml
@model Product

<div class="card my-5">
    <img class="card-img-top" src="~/img/@Model.ImageUrl" alt="@Model.Name universitesi üniversitesi eğitim"  style="height:300px;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <small class="text-muted">
            ne yazsak ki
        </small>
    </div>
    <div class="card-footer text-center" style="border:none;">
        <a asp-controller="shop" asp-action="Details" asp-route-url="@Model.Url" class="btn btn-primary btn-sm">Detaylar</a>
    </div>
</div>   

shopapp.webui/Views/Shared/_search.cshtml
  <div class="card mt-3">
      <div class="card-header">
          <h5>Search</h5>
      </div>
      <div class="card-body">
            <form action="/search">
                <div class="form-group">
                    <input name="q" type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-danger btn-sm btn-block">Ara</button>
            </form>
      </div>
  </div>
  
  

shopapp.webui/Views/Shared/_serve.cshtml
@model Serve

<div class="card" style="padding-top:100px; border:none;">
    <div class="row no-gutters">
        <div class="col-sm-5">
            <img src="~/img/@Model.ServeImageUrl" class="card-img-top" alt="@Model.ServeName eğitim yurtdışı">
        </div>
        <div class="col-sm-7">
            <div class="card-body">
                <h5 class="card-title">@Model.ServeName</h5>
                <p class="card-text">@Model.ServeDescription</p>
            </div>
        </div>
    </div>
</div>